# Generated by Django 4.2.5 on 2025-04-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='faq',
            name='topics',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
