# Generated by Django 4.2.5 on 2025-04-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0003_alter_faq_question_alter_faq_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='question_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
