# Generated by Django 4.2.5 on 2025-03-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='name',
            new_name='sub_category',
        ),
        migrations.AlterField(
            model_name='stock',
            name='sub_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
