# Generated by Django 4.2.5 on 2025-03-15 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_rename_name_category_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name_plural': 'Stock'},
        ),
    ]
