# Generated by Django 4.2.5 on 2025-04-13 09:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_delete_subcategory_remove_category_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dqgc8opao/image/upload/v1744536831/default_image_akymrn.jpg', max_length=255, verbose_name='image'),
        ),
    ]
