# Generated by Django 4.2.5 on 2025-04-13 10:11

from django.db import migrations


def set_default_images(apps, schema_editor):
    Stock = apps.get_model('stock', 'Stock')
    for item in Stock.objects.all():
        if not item.image:
            item.image = 'https://res.cloudinary.com/dqgc8opao/image/upload/v1744536831/default_image_akymrn.jpg'
            item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_stock_image'),
    ]

    operations = [
        migrations.RunPython(set_default_images),
    ]
