# Generated by Django 4.2.5 on 2025-04-15 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_add_default_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='rating',
        ),
    ]
