# Generated by Django 4.2.5 on 2025-04-12 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettersignup',
            name='date_unsubscribed',
        ),
    ]
