# Generated by Django 4.2.5 on 2025-04-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_remove_newslettersignup_date_unsubscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersignup',
            name='date_unsubscribed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newslettersignup',
            name='unsubscribed',
            field=models.BooleanField(default=False),
        ),
    ]
