# Generated by Django 4.2.5 on 2025-04-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_newslettersignup_date_unsubscribed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersignup',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
