# Generated by Django 4.2.5 on 2025-04-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='stock_colour',
            field=models.CharField(blank=True, choices=[('red', 'Red'), ('pink', 'Pink'), ('blue', 'Blue'), ('green', 'Green'), ('white', 'White'), ('black', 'Black'), ('grey', 'Grey'), ('yellow', 'Yellow')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='stock_weight',
            field=models.CharField(blank=True, choices=[('dk', 'Double Knitting'), ('aran', 'Aran'), ('chunky', 'Chunky'), ('super_chunky', 'Super Chunky')], max_length=20, null=True),
        ),
    ]
